name: CI
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
  job1:
    runs-on: self-hosted
    name: deploy magento to minikube local 3

    - name: Deploy to minikube
      run:
        make step-1
    - name: Display pods
      run:
        kubectl get pods
    - name: Edit host file
      run:
        Add-Content C:\Windows\System32\drivers\etc\hosts "`n"MINIKUBE_IP
      env:
          MINIKUBE_IP: minikube ip

