name: CI
on:
  push:
    branches:
      - 'mage-k8s-cicd'
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: show current path
        run: echo $pwd
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build -f src/Dockerfile -t myapp_prod .
      - name: Push the tagged Docker image
        run: docker push myapp_prod
      - name: Build the latest Docker image
        run: docker build . -f src/Dockerfile -t myapp_prod
      - name: Push the latest Docker image
        run: docker push myapp_prod
