name: CI
on:
  push:
    branches:
      - 'mage-k8s-cicd'
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: show current path
        run: echo $pwd
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Building magento-actions docker image
        run: |
          docker build . --tag ${{ secrets.DOCKER_HUB_USERNAME }}/magek8S:latest --tag ${{ secrets.DOCKER_HUB_USERNAME }}/magek8S:1.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/magek8S:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/magek8S:1.0
